#ifndef SWAY_RENDER_PASSTYPES_HPP
#define SWAY_RENDER_PASSTYPES_HPP

#include <sway/core.hpp>

NS_BEGIN_SWAY()
NS_BEGIN(render)

// OPAQUE, TRANSPARENT
DECLARE_ENUM(PassType, GEOM, FINAL, DEPTH, COLOR, REFRACT, BLENDED, SENTINEL)

NS_END()  // namespace render
NS_END()  // namespace sway

#endif  // SWAY_RENDER_PASSTYPES_HPP
