#ifndef SWAY_RENDER_STAGEGROUPINDEXES_HPP
#define SWAY_RENDER_STAGEGROUPINDEXES_HPP

#include <sway/core.hpp>

NS_BEGIN_SWAY()
NS_BEGIN(render)

DECLARE_ENUM_IDX(StageGroupIndex, IDX_SHADING, IDX_PRESENT, IDX_MANUAL)

NS_END()  // namespace render
NS_END()  // namespace sway

#endif  // SWAY_RENDER_STAGEGROUPINDEXES_HPP
