#ifndef SWAY_RENDER_PASSTYPES_HPP
#define SWAY_RENDER_PASSTYPES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(render)

DECLARE_ENUM(PassType, SHADING, PRESENT, MANUAL)

NAMESPACE_END(render)
NAMESPACE_END(sway)

#endif  // SWAY_RENDER_PASSTYPES_HPP
