#ifndef SWAY_RENDER_SPRITEANIMATIONMODES_HPP
#define SWAY_RENDER_SPRITEANIMATIONMODES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(render)

enum class SpriteAnimationMode : u32_t { ONCE, LOOP };

NAMESPACE_END(render)
NAMESPACE_END(sway)

#endif  // SWAY_RENDER_SPRITEANIMATIONMODES_HPP
